services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: sparktest-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sparktest
      - POSTGRES_USER=sparktest
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sparktest_prod_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sparktest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sparktest -d sparktest"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Next.js application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sparktest-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_USE_RUST_API=true
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sparktest
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Rust backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sparktest-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - RUST_ENV=production
      - RUST_LOG=info
      - DATABASE_URL=postgresql://sparktest:${POSTGRES_PASSWORD:-sparktest_prod_password}@postgres:5432/sparktest
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sparktest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  sparktest:
    driver: bridge

volumes:
  postgres_data:
    driver: local
