# fly.toml app configuration file generated for sparktest-demo
app = 'sparktest-demo'
primary_region = 'sjc'

[build]

[deploy]
  strategy = 'rolling'

[env]
  NODE_ENV = 'production'
  NEXT_TELEMETRY_DISABLED = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/'

[[services]]
  internal_port = 8080
  protocol = 'tcp'

  [[services.ports]]
    port = 8080
    handlers = ['http']

  [[services.http_checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[machine]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'sparktest_data'
  destination = '/data'