# fly.toml app configuration file for SparkTest demo
app = 'sparktest-demo'
primary_region = 'sjc'

[build]

[deploy]
  strategy = 'rolling'

[env]
  NODE_ENV = 'production'
  NEXT_TELEMETRY_DISABLED = '1'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = '10s'
  interval = '30s'
  method = 'GET'
  timeout = '5s'
  path = '/'

[machine]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1