[package]
name = "sparktest-bin"
version = "2.0.0"
edition = "2021"
description = "SparkTest backend server binary"
license = "MIT"
repository = "https://github.com/kevintatou/sparktest"
homepage = "https://github.com/kevintatou/sparktest"
include = ["src/**/*", "Cargo.toml", "migrations/**/*"]

[dependencies]
sparktest-core = { version = "2.0.0", path = "../core" }
sparktest-api = { version = "2.0.0", path = "../api" }
axum = "0.7"
tokio = { version = "1.36", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres", "sqlite", "uuid", "chrono", "macros"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0"