version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: .deploy/Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always

  runner:
    build:
      context: ./
      dockerfile: Dockerfile.runner
    environment:
      GH_RUNNER_TOKEN: ${GH_RUNNER_TOKEN}
    restart: always
