version: '3.8'

services:
  # Frontend Next.js application (MVP mode with local storage)
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: sparktest-frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # MVP: Use local storage instead of backend API
      - NEXT_PUBLIC_USE_RUST_API=false
    networks:
      - sparktest
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend service commented out for MVP deployment
  # To re-enable backend API:
  # 1. Uncomment the backend service below
  # 2. Change NEXT_PUBLIC_USE_RUST_API to true in frontend environment
  # 3. Add "depends_on: - backend" to frontend service
  # 4. Uncomment backend_data volume below
  #
  # backend:
  #   build:
  #     context: ..
  #     dockerfile: .deploy/Dockerfile.backend
  #   container_name: sparktest-backend
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - RUST_ENV=production
  #     - RUST_LOG=info
  #     - DATABASE_URL=sqlite:///app/data/sparktest.db
  #   volumes:
  #     - backend_data:/app/data
  #   networks:
  #     - sparktest
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

networks:
  sparktest:
    driver: bridge

# Uncomment when backend is re-enabled
# volumes:
#   backend_data:
#     driver: local
