name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  frontend:
    name: Frontend Tests & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Run tests with coverage
        run: pnpm run coverage
      - name: Upload frontend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/lcov.info

  backend:
    name: Backend Tests & Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run backend tests with coverage
        run: cargo tarpaulin --out Lcov --output-dir coverage
      - name: Upload backend coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/lcov.info

  combine-coverage:
    name: Combine Coverage and Report
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - uses: actions/checkout@v4
      - name: Download frontend coverage
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: coverage-frontend
      - name: Download backend coverage
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: coverage-backend
      - name: Combine lcov reports
        run: |
          mkdir -p coverage-combined
          cat coverage-frontend/lcov.info coverage-backend/lcov.info > coverage-combined/lcov.info
      - name: Report overall coverage (Codecov)
        uses: codecov/codecov-action@v4
        with:
          files: coverage-combined/lcov.info
          flags: overall
          fail_ci_if_error: true
      - name: Show overall coverage summary
        run: |
          npx lcov-result-merger coverage-frontend/lcov.info coverage-backend/lcov.info > merged.info
          npx lcov-summary merged.info
