name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting
        run: pnpm format:check

      - name: Run linting
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Build workspace packages
        run: pnpm build:packages

      - name: Build application
        run: pnpm --filter "@sparktest/oss" build

      - name: Run tests
        run: pnpm test

      - name: Run E2E tests
        run: pnpm --filter "@sparktest/oss" test:e2e
        env:
          CI: true
