name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Enable Corepack and install pnpm
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: apps/oss/pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install
      working-directory: apps/oss

    - name: Build application
      run: pnpm build
      working-directory: apps/oss

    - name: Run E2E tests
      run: pnpm test:e2e
      working-directory: apps/oss
      env:
        CI: true
