name: Publish Rust Crates

on:
  push:
    tags:
      - 'crate-v*'

permissions:
  contents: read

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run tests
        run: cargo test --verbose
        working-directory: backend

      - name: Publish sparktest-core
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path backend/core/Cargo.toml

      - name: Wait for crate to be available
        run: sleep 30

      - name: Publish sparktest-api
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path backend/api/Cargo.toml

      - name: Wait for crate to be available
        run: sleep 30

      - name: Publish sparktest-bin
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path backend/bin/Cargo.toml